services:
  # A Docker web service
  - type: web
    name: Linkbricks-AI Workflow Advanced
    runtime: docker
    dockerfilePath: ./docker/render.Dockerfile
    repo: https://github.com/saxoji/langflow
    branch: main
    plan: Pro Plus
    healthCheckPath: /health_check
    autoDeploy: true
    envVars:
      - key: LANGFLOW_DATABASE_URL
        value: sqlite:////app/data/.cache/langflow/langflow.db
      - key: LANGFLOW_HOST
        value: 0.0.0.0
      - key: LANGFLOW_PORT
        # default render port https://docs.render.com/web-services#port-binding
        value: 10000
      - key: LANGFLOW_LOG_LEVEL
        value: INFO
      - key: LANGFLOW_AUTO_LOGIN
        value: false
      - key: LANGFLOW_SUPERUSER
        value: linkbricks
      - key: LANGFLOW_SUPERUSER_PASSWORD
        value: Linkbricks!123
    disk:
      name: langflow-data
      mountPath: /app/data
